### ISSUE TITLE
I cannot get the position of my character to move (Main.cs)

### ISSUE THREAD

**Issue by itsme-hayden** [itsme-hayden/wintergame#20]
I followed a tutorial in trying to create the Dino Runner game, but I am _running_ into an issue that has cost me hours of my life. 
![image](https://github.com/user-attachments/assets/8c2f7139-ef58-46db-a27c-d2cfe930280e)
The above image shows the code I am working with, which is in GDscript. I thought I had translated it as best I could, but I ran into a constant error in which 

`_dino.Position.X += speed`

would throw an error 

`CS1612: Cannot modify the return value of 'Node2D.Position' because it is not a variable`

The error code references this [Microsoft page](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1612) 

I then tried copying some code Joe had written.
Then, I tried looking at example Godot projects to see how they were moving characters. 
And looking at all these different things and trying to implement them simultaneously left me confused and my code a mess. 

I need to be able to move the camera and the player at the same speed at the same time so that the player remains at the same spot on the screen and objects come toward the player. Other approaches would be helpful, but I am tired of using this GDscript tutorial.

So please, help me, Obi-Wan Kenobi, you're my only hope.

**Comment by itsme-hayden** [comment]
![image](https://github.com/user-attachments/assets/833af1d2-a8f7-4e50-8a4a-cff6d4c4b58a)
Here is my embarrassing mess of code, by the way.

**Comment by JBB248** [comment]
Well, you can probably just use `LinearVelocity`

**Comment by JBB248** [comment]
I don't think it needs to move horizontally, though. You can just make the environment move towards it.

**Comment by itsme-hayden** [comment]
I addressed why I did what I am trying to do in the discussion with the pull request. However, I may end up changing it to be that way anyway, we'll see how it goes.
